## Name of the CI/CD Pipeline
##
name: Build APK(unsigned), Upload Artifact & Upload on firebase

##
## This is the trigger which will initiate our workflow
##


## We are initializing workflow whenever we push new code to any branch on repo
on: [push]

## Adding a button to trigger workflow manually
  workflow_dispatch:


##
## This is a job in our workflow, the name of job is "build-deploy"
jobs:
  build-deploy:

## This is the OS on which we would like to run our job, we can choose windows, macOS or Linux
    runs-on: ubuntu-latest
    steps:
## In this step,
## The Github Repo in which this .yaml file resides is cloned
      - uses: actions/checkout@v3
## Setting up JAVA Environment
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12.x"
## Setting up the flutter environment
## 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: "stable"
## This step is used add google-services.json, firebase_options.dart files to our project, 
## remember we cannot push these files into repo for security reasons,
## We are fetching each file fom Github Secrets and then including in project at time of execution
##
      - name: Decode google-services.json
        env: 
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTION}}
        run: echo "$firebase_options_dart" > lib/firebase_options.dart
## Fetching flutter dependencies and building a release apk file
##
      - run: flutter pub get
      - run: flutter build apk

## Uploading the generated apk (we call it artifact in github terms) so it is accessible anytime when we comeback 
## Artifacts can be anything that we want to save/persists for future use after our workflow/job has finished
## Github by default saves log files as artifcats too
## Artifacts are auto-deleted after 90 days in free/normal GitHub plans, This timeframe can be increase with paid subscriptions

      - uses: actions/upload-artifact@v2  
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

##  Upload to Firebase, via 
##
      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}} #deprecated method, use service account
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: build/app/outputs/flutter-apk/app-release.apk
