name: Build and Deploy Flutter Web
on:
  push:
    branches:
      - main

jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
    - run: flutter pub get
    - run: flutter config --enable-web ## not needed in case of new flutter
    - run: flutter build web

    - name: 📂 Deploy to name-cheap
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER}}
        username: ${{ secrets.FTP_USER}}
        password: ${{ secrets.FTP_PASSWORD}}
        local-dir: build/web/

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --public build/web
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}