name: CI CD Pipeline

on:
  push:
    branches: 
     - 'main'

jobs:
#this job is used to build the app only when we use a release keyword
  build-app:
    name: Build Flutter App
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12.x"
 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.4"
          channel: "stable"

      - run: flutter pub get
      - run: flutter build apk --release

    


      - uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.APP_ID}}
            token: ${{secrets.TOKEN}}
            groups: internal-group
            file: build/app/outputs/flutter-apk/app-release.apk
      - if: contains(github.event.head_commit.message, 'external-release')
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.APP_ID}}
            token: ${{secrets.TOKEN}}
            groups: external-group
            file: build/app/outputs/flutter-apk/app-release.apk
## This will upload the generated artifacts so we may be able to download them
## 
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab


