name: Flutter Build APK

on:
  push:

jobs:
  build-app:
    name: Build Flutter App
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "12.x"
 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.4"
          channel: "stable"

      - run: flutter pub get
      - run: flutter build apk --release
      - run: flutter build appbundle
    
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
    
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt
  build2:
    needs: build-app
    name: upload to internal developers
    if: contains(github.event.head_commit.message, 'internal')
    runs-on: ubuntu-latest
    steps:
      - run: echo internal job should be printed
      - run: echo 
  build3:
    needs: build-app
    name: upload to external developers
    if: contains(github.event.head_commit.message, 'external')
    runs-on: ubuntu-latest
    steps:
      - run: echo external job should be printed

  internal-release:
    if: contains(github.event.head_commit.message, 'internal-release')
    needs: build-app
    name: uploading apk file
    runs-on: ubuntu-latest
    steps:
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.APP_ID}}
            token: ${{secrets.TOKEN}}
            groups: internal-group
            file: build/app/outputs/apk/release/app-release.apk
  external-release:
    if: contains(github.event.head_commit.message, 'external-release')
    needs: build-app
    name: uploading apk file
    runs-on: ubuntu-latest
    steps:   
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{secrets.APP_ID}}
            token: ${{secrets.TOKEN}}
            groups: external-group
            file: build/app/outputs/apk/release/app-release.apk

  