name: React App Deployment Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm ci
      - run: CI=false npm run build
      - if: contains(github.event.head_commit.message, 'release')
        name: Deploy to NameCheap
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USER}}
          password: ${{ secrets.FTP_PASSWORD}}
          port: ${{secrets.FTP_PORT}}
          local-dir: ./build